version: '3.7'

services:

  mariadb:
    build:
      context: ./data
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - '3306:3306'

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
      args:
        DATABASE_URL: mysql://myuser:mypassword@mariadb:3306/gauge@gauge
    restart: on-failure
    depends_on:
      - mariadb

  gauge:
    build:
      context: .
    environment:
      LOG_LEVEL: "debug"
    depends_on:
      - mariadb
      - migration
    restart: on-failure
    ports:
      - '80:80'

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
    links:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100
