CREATE TABLE IF NOT EXISTS `gauge@gauge`.gauge (
name VARCHAR(36) NOT NULL,
value BIGINT NOT NULL DEFAULT 0,
last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (name)
) ENGINE=INNODB;