{
 "title": "Persistent Guage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Persistent Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "persistent_gauge", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(http_requests_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_duration_seconds_count{status=\"200\"}[2m])) by (pod) / sum(irate(http_requests_duration_seconds_count[2m])) by (pod)",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_duration_seconds_count[2m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Get Gauge Latency, event rate [2m]",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_requests_duration_seconds_bucket{path=\"/api/gauge/gauges\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Get Gauge Latency, event rate [2m]",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_requests_duration_seconds_bucket{path=\"/api/gauge/increment/:gauge_name\"}[2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}